coverage:
  precision: 2
  round: down
  range: "70...100"

ignore:
  - "node_modules"
  - "coverage"
  - "android"
  - "ios"
  - "**/*.d.ts"
  - "**/__tests__/**"

comment:
  layout: reach,diff,flags,tree
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

status:
  changes: true
  patch: true
  project: true
