name: Setup Environment

description: Common setup for Node, Java, Expo/EAS and dependencies

inputs:
  expo-token:
    description: "Expo token"
    required: true

runs:
  using: "composite"
  steps:

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "22"
        cache: "npm"

    - name: Setup Expo & EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.expo-token }}

    - name: Cache Expo
      uses: actions/cache@v5
      with:
        path: |
          ~/.expo
          ~/.eas
        key: ${{ runner.os }}-expo-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-expo-

    - name: Install dependencies
      run: npm i
      shell: bash