name: update
on: push

jobs:
  android-publish:
    name: Android build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Replace Tokens
        run: |
          sed -i 's/FB_SDK_CLIENT_TOKEN/${{ secrets.FB_SDK_CLIENT_TOKEN }}/' app.json;
          cat app.json;
          sed -i 's/GOOGLE_PLAY_CURRENT_KEY/${{ secrets.GOOGLE_PLAY_CURRENT_KEY }}/' google-services.json;
          cat google-services.json;
          sed -i 's/GOOGLE_PLAY_PRIVATE_KEY_ID/${{ secrets.GOOGLE_PLAY_PRIVATE_KEY_ID }}/' pc-api-9058583074469096499-576-79a2369c84f6.json;
          sed -i 's/GOOGLE_PLAY_PRIVATE_KEY/${{ secrets.GOOGLE_PLAY_PRIVATE_KEY }}/' pc-api-9058583074469096499-576-79a2369c84f6.json;
          sed -i 's/GOOGLE_PLAY_CLIENT_ID/${{ secrets.GOOGLE_PLAY_CLIENT_ID }}/' pc-api-9058583074469096499-576-79a2369c84f6.json;
          cat pc-api-9058583074469096499-576-79a2369c84f6.json;

      - name: Install dependencies
        run: npm install

      - name: build
        run: eas build --profile production --platform android --non-interactive

      - name: publish to play store
        run: eas submit -p android --latest
